name: Continuous Integration

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ github.actor }}
  DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and Publish with Gradle
        env:
          # GitHub Actions has 7GBs of available RAM for workers, so let's bump it a bit up!
          GRADLE_OPTS: -Xmx4096m -Xms4096m
          ORG_GRADLE_PROJECT_PerfectDreamsUsername: ${{ secrets.PERFECTDREAMS_REPO_USERNAME }}
          ORG_GRADLE_PROJECT_PerfectDreamsPassword: ${{ secrets.PERFECTDREAMS_REPO_PASSWORD }}
        run: ./gradlew build assembleDist publish --scan

      - name: Upload CLI tools
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
        run: |
          gh release create ${{ steps.vars.outputs.sha_short }} --draft --title ${{ steps.vars.outputs.sha_short }} --notes "Automated Release"
          gh release upload ${{ steps.vars.outputs.sha_short }} floormaker-cli/build/distributions/*
          gh release upload ${{ steps.vars.outputs.sha_short }} wallpapermaker-cli/build/distributions/*
          gh release upload ${{ steps.vars.outputs.sha_short }} iffchunkdumper-cli/build/distributions/*
          gh release edit ${{ steps.vars.outputs.sha_short }} --draft=false
