name: Continuous Integration

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: "${{ github.actor }}"
  DOCKER_PASSWORD: "${{ secrets.GITHUB_TOKEN }}"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "gradle"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and Publish with Gradle
        env:
          # GitHub Actions has 7GBs of available RAM for workers, so let's bump it a bit up!
          GRADLE_OPTS: -Xmx4096m -Xms4096m
          ORG_GRADLE_PROJECT_PerfectDreamsUsername: ${{ secrets.PERFECTDREAMS_REPO_USERNAME }}
          ORG_GRADLE_PROJECT_PerfectDreamsPassword: ${{ secrets.PERFECTDREAMS_REPO_PASSWORD }}
        run: ./gradlew build assembleDist publish --scan

      - name: Upload CLI tools
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
        run: |
          gh release create "${{ github.sha }}" --draft --title "${{ github.sha }}" --notes "Automated Release"
          gh release upload "${{ github.sha }}" floormaker-cli/build/distributions/*
          gh release upload "${{ github.sha }}" wallpapermaker-cli/build/distributions/*
          gh release edit "${{ github.sha }}" --draft=false
          
          
